development:
  stripe_secret_key: 'sk_test_51LYBP3SDMv4dgdhUer8AFidk7ps2wzP90UWfDQtmzOQjYV9JgZW9mxQBHkPEqWlVs03iGGba36iMRSZtriRUmQaL00h22bVlg1'
  stripe_publishable_key: 'pk_test_51LYBP3SDMv4dgdhUuXg4GRYzL5LI0pRTZf1tMwC2pJ03mnG8ttvv91y0hVBfeMGip5kSAczZRLfEMYJWNSpuHSTT00lH4wNHJJ'

# production:
  # stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  # stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'